# Generated by Django 4.1.7 on 2023-03-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_first', '0002_remove_comment_date_comment_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
